### ISSUE TITLE
Error 290 when installing package built by the script

### ISSUE THREAD

**Issue by cardinal-tom** [raman325/syno-wg-autoinstaller#1]
Hi, I'm having a problem with this very useful script. It runs fine (once I'd installed the Docker and Git Server packages), but then I get an error near what I assume is the end of the script, where it installs the .spk file it created for my device. I've attached the log
[Wireguard update script log.txt](https://github.com/raman325/syno-wg-autoinstaller/files/5062507/Wireguard.update.script.log.txt)

**Comment by cardinal-tom** [comment]
Okay, I found the source of the problem: it's necessary to set the trust level to "Any publisher" in the Package Center settings.

**Comment by raman325** [comment]
Thanks for the heads up, I will make a note of this!
